version: '3'

services:
  dropbox-service:
    image: dropbox-service
    build: .
    env_file:
      - ../kdrive.env
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - elasticsearch
      - spike-service
      - user-service
  
  spike-service:
    image: drivehub.azurecr.io/meateam/spike-service:develop
    ports:
      - "8081:8080"
    env_file:
      - ../kdrive.env
    depends_on:
      - redis

  user-service:
    image: drivehub.azurecr.io/meateam/user-service:develop
    ports:
      - "8082:8080"
    env_file:
      - ../kdrive.env
    depends_on:
      - mongo
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongo:
    image: mongo:4.0.9
    ports:
      - "27017:27017"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.0"
    environment:
      - discovery.type=single-node
    container_name: elasticsearch
    ports:
      - "9200:9200"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:9200"
      interval: 5s
      timeout: 10s
      retries: 5