// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dropbox/dropbox.proto

package dropbox

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetApproverInfoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApproverInfoRequest) Reset()         { *m = GetApproverInfoRequest{} }
func (m *GetApproverInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetApproverInfoRequest) ProtoMessage()    {}
func (*GetApproverInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{0}
}

func (m *GetApproverInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApproverInfoRequest.Unmarshal(m, b)
}
func (m *GetApproverInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApproverInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetApproverInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApproverInfoRequest.Merge(m, src)
}
func (m *GetApproverInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetApproverInfoRequest.Size(m)
}
func (m *GetApproverInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApproverInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApproverInfoRequest proto.InternalMessageInfo

func (m *GetApproverInfoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetApproverInfoRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type GetApproverInfoResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsAdmin              bool     `protobuf:"varint,2,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	IsApprover           bool     `protobuf:"varint,3,opt,name=isApprover,proto3" json:"isApprover,omitempty"`
	IsBlocked            bool     `protobuf:"varint,4,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	UnitName             string   `protobuf:"bytes,5,opt,name=unitName,proto3" json:"unitName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApproverInfoResponse) Reset()         { *m = GetApproverInfoResponse{} }
func (m *GetApproverInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetApproverInfoResponse) ProtoMessage()    {}
func (*GetApproverInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{1}
}

func (m *GetApproverInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApproverInfoResponse.Unmarshal(m, b)
}
func (m *GetApproverInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApproverInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetApproverInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApproverInfoResponse.Merge(m, src)
}
func (m *GetApproverInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetApproverInfoResponse.Size(m)
}
func (m *GetApproverInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApproverInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApproverInfoResponse proto.InternalMessageInfo

func (m *GetApproverInfoResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetApproverInfoResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *GetApproverInfoResponse) GetIsApprover() bool {
	if m != nil {
		return m.IsApprover
	}
	return false
}

func (m *GetApproverInfoResponse) GetIsBlocked() bool {
	if m != nil {
		return m.IsBlocked
	}
	return false
}

func (m *GetApproverInfoResponse) GetUnitName() string {
	if m != nil {
		return m.UnitName
	}
	return ""
}

type CanApproveToUserRequest struct {
	ApproverID           string   `protobuf:"bytes,1,opt,name=approverID,proto3" json:"approverID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanApproveToUserRequest) Reset()         { *m = CanApproveToUserRequest{} }
func (m *CanApproveToUserRequest) String() string { return proto.CompactTextString(m) }
func (*CanApproveToUserRequest) ProtoMessage()    {}
func (*CanApproveToUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{2}
}

func (m *CanApproveToUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanApproveToUserRequest.Unmarshal(m, b)
}
func (m *CanApproveToUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanApproveToUserRequest.Marshal(b, m, deterministic)
}
func (m *CanApproveToUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanApproveToUserRequest.Merge(m, src)
}
func (m *CanApproveToUserRequest) XXX_Size() int {
	return xxx_messageInfo_CanApproveToUserRequest.Size(m)
}
func (m *CanApproveToUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CanApproveToUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CanApproveToUserRequest proto.InternalMessageInfo

func (m *CanApproveToUserRequest) GetApproverID() string {
	if m != nil {
		return m.ApproverID
	}
	return ""
}

func (m *CanApproveToUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CanApproveToUserRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type CanApproveToUserResponse struct {
	CanApproveToUser     bool     `protobuf:"varint,1,opt,name=canApproveToUser,proto3" json:"canApproveToUser,omitempty"`
	CantApproveReasons   []string `protobuf:"bytes,2,rep,name=cantApproveReasons,proto3" json:"cantApproveReasons,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanApproveToUserResponse) Reset()         { *m = CanApproveToUserResponse{} }
func (m *CanApproveToUserResponse) String() string { return proto.CompactTextString(m) }
func (*CanApproveToUserResponse) ProtoMessage()    {}
func (*CanApproveToUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{3}
}

func (m *CanApproveToUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanApproveToUserResponse.Unmarshal(m, b)
}
func (m *CanApproveToUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanApproveToUserResponse.Marshal(b, m, deterministic)
}
func (m *CanApproveToUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanApproveToUserResponse.Merge(m, src)
}
func (m *CanApproveToUserResponse) XXX_Size() int {
	return xxx_messageInfo_CanApproveToUserResponse.Size(m)
}
func (m *CanApproveToUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CanApproveToUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CanApproveToUserResponse proto.InternalMessageInfo

func (m *CanApproveToUserResponse) GetCanApproveToUser() bool {
	if m != nil {
		return m.CanApproveToUser
	}
	return false
}

func (m *CanApproveToUserResponse) GetCantApproveReasons() []string {
	if m != nil {
		return m.CantApproveReasons
	}
	return nil
}

type CreateRequestRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	SharerID             string   `protobuf:"bytes,2,opt,name=sharerID,proto3" json:"sharerID,omitempty"`
	Users                []*User  `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Classification       string   `protobuf:"bytes,4,opt,name=classification,proto3" json:"classification,omitempty"`
	Info                 string   `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	Approvers            []string `protobuf:"bytes,6,rep,name=approvers,proto3" json:"approvers,omitempty"`
	FileName             string   `protobuf:"bytes,7,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Destination          string   `protobuf:"bytes,8,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequestRequest) Reset()         { *m = CreateRequestRequest{} }
func (m *CreateRequestRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequestRequest) ProtoMessage()    {}
func (*CreateRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{4}
}

func (m *CreateRequestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequestRequest.Unmarshal(m, b)
}
func (m *CreateRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequestRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequestRequest.Merge(m, src)
}
func (m *CreateRequestRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequestRequest.Size(m)
}
func (m *CreateRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequestRequest proto.InternalMessageInfo

func (m *CreateRequestRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *CreateRequestRequest) GetSharerID() string {
	if m != nil {
		return m.SharerID
	}
	return ""
}

func (m *CreateRequestRequest) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *CreateRequestRequest) GetClassification() string {
	if m != nil {
		return m.Classification
	}
	return ""
}

func (m *CreateRequestRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *CreateRequestRequest) GetApprovers() []string {
	if m != nil {
		return m.Approvers
	}
	return nil
}

func (m *CreateRequestRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CreateRequestRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRequestResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequestResponse) Reset()         { *m = CreateRequestResponse{} }
func (m *CreateRequestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRequestResponse) ProtoMessage()    {}
func (*CreateRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{6}
}

func (m *CreateRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequestResponse.Unmarshal(m, b)
}
func (m *CreateRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequestResponse.Marshal(b, m, deterministic)
}
func (m *CreateRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequestResponse.Merge(m, src)
}
func (m *CreateRequestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRequestResponse.Size(m)
}
func (m *CreateRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequestResponse proto.InternalMessageInfo

type HasTransferRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasTransferRequest) Reset()         { *m = HasTransferRequest{} }
func (m *HasTransferRequest) String() string { return proto.CompactTextString(m) }
func (*HasTransferRequest) ProtoMessage()    {}
func (*HasTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{7}
}

func (m *HasTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasTransferRequest.Unmarshal(m, b)
}
func (m *HasTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasTransferRequest.Marshal(b, m, deterministic)
}
func (m *HasTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasTransferRequest.Merge(m, src)
}
func (m *HasTransferRequest) XXX_Size() int {
	return xxx_messageInfo_HasTransferRequest.Size(m)
}
func (m *HasTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HasTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HasTransferRequest proto.InternalMessageInfo

func (m *HasTransferRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *HasTransferRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *HasTransferRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type HasTransferResponse struct {
	HasTransfer          bool     `protobuf:"varint,1,opt,name=hasTransfer,proto3" json:"hasTransfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasTransferResponse) Reset()         { *m = HasTransferResponse{} }
func (m *HasTransferResponse) String() string { return proto.CompactTextString(m) }
func (*HasTransferResponse) ProtoMessage()    {}
func (*HasTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{8}
}

func (m *HasTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasTransferResponse.Unmarshal(m, b)
}
func (m *HasTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasTransferResponse.Marshal(b, m, deterministic)
}
func (m *HasTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasTransferResponse.Merge(m, src)
}
func (m *HasTransferResponse) XXX_Size() int {
	return xxx_messageInfo_HasTransferResponse.Size(m)
}
func (m *HasTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HasTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HasTransferResponse proto.InternalMessageInfo

func (m *HasTransferResponse) GetHasTransfer() bool {
	if m != nil {
		return m.HasTransfer
	}
	return false
}

type GetTransfersInfoRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransfersInfoRequest) Reset()         { *m = GetTransfersInfoRequest{} }
func (m *GetTransfersInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransfersInfoRequest) ProtoMessage()    {}
func (*GetTransfersInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{9}
}

func (m *GetTransfersInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransfersInfoRequest.Unmarshal(m, b)
}
func (m *GetTransfersInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransfersInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetTransfersInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransfersInfoRequest.Merge(m, src)
}
func (m *GetTransfersInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransfersInfoRequest.Size(m)
}
func (m *GetTransfersInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransfersInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransfersInfoRequest proto.InternalMessageInfo

func (m *GetTransfersInfoRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *GetTransfersInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetTransfersInfoRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type GetTransfersInfoResponse struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	To                   []*User  `protobuf:"bytes,6,rep,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransfersInfoResponse) Reset()         { *m = GetTransfersInfoResponse{} }
func (m *GetTransfersInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransfersInfoResponse) ProtoMessage()    {}
func (*GetTransfersInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51df0dd507690321, []int{10}
}

func (m *GetTransfersInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransfersInfoResponse.Unmarshal(m, b)
}
func (m *GetTransfersInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransfersInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetTransfersInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransfersInfoResponse.Merge(m, src)
}
func (m *GetTransfersInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransfersInfoResponse.Size(m)
}
func (m *GetTransfersInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransfersInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransfersInfoResponse proto.InternalMessageInfo

func (m *GetTransfersInfoResponse) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *GetTransfersInfoResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetTransfersInfoResponse) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *GetTransfersInfoResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetTransfersInfoResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GetTransfersInfoResponse) GetTo() []*User {
	if m != nil {
		return m.To
	}
	return nil
}

func init() {
	proto.RegisterType((*GetApproverInfoRequest)(nil), "dropbox.GetApproverInfoRequest")
	proto.RegisterType((*GetApproverInfoResponse)(nil), "dropbox.GetApproverInfoResponse")
	proto.RegisterType((*CanApproveToUserRequest)(nil), "dropbox.CanApproveToUserRequest")
	proto.RegisterType((*CanApproveToUserResponse)(nil), "dropbox.CanApproveToUserResponse")
	proto.RegisterType((*CreateRequestRequest)(nil), "dropbox.CreateRequestRequest")
	proto.RegisterType((*User)(nil), "dropbox.User")
	proto.RegisterType((*CreateRequestResponse)(nil), "dropbox.CreateRequestResponse")
	proto.RegisterType((*HasTransferRequest)(nil), "dropbox.HasTransferRequest")
	proto.RegisterType((*HasTransferResponse)(nil), "dropbox.HasTransferResponse")
	proto.RegisterType((*GetTransfersInfoRequest)(nil), "dropbox.GetTransfersInfoRequest")
	proto.RegisterType((*GetTransfersInfoResponse)(nil), "dropbox.GetTransfersInfoResponse")
}

func init() {
	proto.RegisterFile("dropbox/dropbox.proto", fileDescriptor_51df0dd507690321)
}

var fileDescriptor_51df0dd507690321 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x6e, 0xe2, 0x34, 0x49, 0x27, 0x6a, 0x7f, 0xd5, 0xfc, 0x68, 0x63, 0x85, 0xb6, 0x04, 0x23,
	0xa1, 0xaa, 0x87, 0x20, 0x95, 0x03, 0xe7, 0xd0, 0x48, 0x40, 0x0f, 0x08, 0x59, 0x05, 0x89, 0xe3,
	0xd6, 0x5e, 0xab, 0xab, 0x26, 0xde, 0xe0, 0xdd, 0x54, 0xbc, 0x01, 0x4f, 0xc2, 0x23, 0x70, 0xe4,
	0xdd, 0x58, 0xaf, 0x77, 0x6d, 0xc7, 0x7f, 0x40, 0x42, 0x9c, 0xba, 0xf3, 0x4d, 0x76, 0x66, 0xbe,
	0x6f, 0xbe, 0x75, 0xe1, 0x28, 0x4c, 0xf8, 0xfa, 0x96, 0x7f, 0x7d, 0x61, 0xfe, 0xce, 0xd6, 0x09,
	0x97, 0x1c, 0x07, 0x26, 0xf4, 0xae, 0xe1, 0xf8, 0x0d, 0x95, 0xf3, 0xb5, 0x82, 0x1f, 0x68, 0xf2,
	0x2e, 0x8e, 0xb8, 0x4f, 0xbf, 0x6c, 0xa8, 0x90, 0x78, 0x00, 0x5d, 0x16, 0xba, 0x9d, 0x69, 0xe7,
	0x7c, 0xcf, 0x57, 0x27, 0x9c, 0xc2, 0x28, 0x54, 0x38, 0x8b, 0x89, 0x64, 0x3c, 0x76, 0xbb, 0x3a,
	0x51, 0x86, 0xbc, 0xef, 0x1d, 0x18, 0xd7, 0x8a, 0x89, 0x35, 0x8f, 0x05, 0xc5, 0x63, 0xe8, 0x6f,
	0x84, 0xc2, 0x6c, 0x45, 0x13, 0xa1, 0x0b, 0x03, 0x26, 0xe6, 0xe1, 0x8a, 0x65, 0x15, 0x87, 0xbe,
	0x0d, 0xf1, 0x0c, 0x40, 0x1d, 0x4d, 0x2d, 0xd7, 0xd1, 0xc9, 0x12, 0x82, 0x27, 0xb0, 0xc7, 0xc4,
	0xeb, 0x25, 0x0f, 0xee, 0x69, 0xe8, 0xf6, 0x74, 0xba, 0x00, 0x70, 0x02, 0xc3, 0x4d, 0xcc, 0xe4,
	0x7b, 0xb2, 0xa2, 0xee, 0xae, 0xee, 0x98, 0xc7, 0x9e, 0x80, 0xf1, 0x15, 0x89, 0x4d, 0xa1, 0x1b,
	0xfe, 0x51, 0x4d, 0x62, 0x49, 0xab, 0xa6, 0xc4, 0x8e, 0xbf, 0x30, 0xa3, 0x96, 0x90, 0x9c, 0xc6,
	0xc2, 0xf0, 0x37, 0x51, 0x55, 0x1c, 0xa7, 0x2e, 0xce, 0x03, 0xb8, 0xf5, 0xa6, 0x46, 0x9c, 0x0b,
	0x38, 0x0c, 0x2a, 0x39, 0xdd, 0x7b, 0xe8, 0xd7, 0x70, 0x9c, 0x01, 0x2a, 0xcc, 0x8a, 0xec, 0x53,
	0x22, 0x54, 0x09, 0x35, 0x8d, 0xa3, 0x1a, 0x36, 0x64, 0xbc, 0x6f, 0x5d, 0x78, 0x74, 0x95, 0x50,
	0x22, 0xa9, 0xe1, 0x68, 0xa9, 0x2a, 0x2a, 0x11, 0x5b, 0xd2, 0x9c, 0xa6, 0x89, 0x52, 0xe5, 0xc4,
	0x1d, 0x49, 0x4a, 0x24, 0xf3, 0x18, 0x9f, 0xc1, 0x6e, 0x4a, 0x58, 0x28, 0x82, 0xce, 0xf9, 0xe8,
	0x72, 0x7f, 0x66, 0x5d, 0xa5, 0xe9, 0x64, 0x39, 0x7c, 0x0e, 0x07, 0xc1, 0x92, 0x08, 0xc1, 0x22,
	0x16, 0x64, 0x72, 0xf4, 0x74, 0x99, 0x0a, 0x8a, 0x08, 0x3d, 0xa6, 0x2c, 0x62, 0xd6, 0xa3, 0xcf,
	0xe9, 0x52, 0xad, 0xda, 0xc2, 0xed, 0x6b, 0x52, 0x05, 0x90, 0x8e, 0x96, 0x0e, 0xa9, 0x97, 0x3a,
	0xc8, 0x46, 0xb3, 0x71, 0x75, 0x03, 0xc3, 0xfa, 0x06, 0x2e, 0xa0, 0xa7, 0x15, 0xac, 0x1a, 0x5b,
	0xcd, 0x11, 0xa7, 0x15, 0x33, 0xb2, 0xfa, 0xec, 0x8d, 0xe1, 0xa8, 0x22, 0x5a, 0xb6, 0x2a, 0x2f,
	0x02, 0x7c, 0x4b, 0xc4, 0x4d, 0x42, 0x62, 0x11, 0x15, 0xb6, 0x69, 0xd3, 0xf2, 0xef, 0xed, 0xf2,
	0x0a, 0xfe, 0xdf, 0xea, 0x63, 0x9c, 0xa2, 0x2e, 0xde, 0x15, 0xb0, 0x31, 0x49, 0x19, 0xf2, 0xee,
	0xf5, 0x1b, 0xb4, 0xa1, 0x28, 0xbf, 0xe8, 0x7f, 0x3f, 0xe5, 0xcf, 0x0e, 0xb8, 0xf5, 0x6e, 0xc5,
	0x93, 0x6f, 0x6c, 0xa7, 0xf4, 0x8e, 0x12, 0xbe, 0xb2, 0x7a, 0xa7, 0xe7, 0x3f, 0xb7, 0x4a, 0xab,
	0x09, 0x49, 0xe4, 0x46, 0x18, 0x37, 0x99, 0x28, 0x75, 0x4c, 0xa0, 0x37, 0x15, 0xce, 0xa5, 0xb6,
	0x92, 0xe3, 0x17, 0x00, 0x9e, 0x42, 0x57, 0x72, 0x6d, 0xa4, 0x9a, 0x5b, 0x55, 0xe2, 0xf2, 0x87,
	0x03, 0x83, 0x45, 0x06, 0xe2, 0x27, 0xf8, 0xaf, 0xf2, 0xf1, 0xc2, 0x27, 0xf9, 0x8d, 0xe6, 0x6f,
	0xe4, 0x64, 0xda, 0xfe, 0x03, 0xe3, 0x97, 0x1d, 0xfc, 0x0c, 0x87, 0xd5, 0x87, 0x8f, 0xc5, 0xbd,
	0x96, 0x0f, 0xd1, 0xe4, 0xe9, 0x6f, 0x7e, 0x91, 0x97, 0xfe, 0x00, 0xfb, 0x5b, 0x2e, 0xc5, 0xd3,
	0xe2, 0x56, 0xc3, 0x93, 0x9f, 0x9c, 0xb5, 0xa5, 0xf3, 0x8a, 0xd7, 0x30, 0x2a, 0xd9, 0x0e, 0x1f,
	0xe7, 0x17, 0xea, 0xa6, 0x9f, 0x9c, 0x34, 0x27, 0xcb, 0xc4, 0xab, 0xde, 0xc0, 0x2d, 0xc1, 0x9a,
	0x4c, 0x5a, 0x22, 0xde, 0x66, 0x2c, 0x6f, 0xe7, 0xb6, 0xaf, 0xff, 0x8b, 0xbd, 0xfc, 0x15, 0x00,
	0x00, 0xff, 0xff, 0x4b, 0x3a, 0x7f, 0x38, 0xde, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DropboxClient is the client API for Dropbox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DropboxClient interface {
	GetApproverInfo(ctx context.Context, in *GetApproverInfoRequest, opts ...grpc.CallOption) (*GetApproverInfoResponse, error)
	CanApproveToUser(ctx context.Context, in *CanApproveToUserRequest, opts ...grpc.CallOption) (*CanApproveToUserResponse, error)
	CreateRequest(ctx context.Context, in *CreateRequestRequest, opts ...grpc.CallOption) (*CreateRequestResponse, error)
	HasTransfer(ctx context.Context, in *HasTransferRequest, opts ...grpc.CallOption) (*HasTransferResponse, error)
	GetTransfersInfo(ctx context.Context, in *GetTransfersInfoRequest, opts ...grpc.CallOption) (*GetTransfersInfoResponse, error)
}

type dropboxClient struct {
	cc grpc.ClientConnInterface
}

func NewDropboxClient(cc grpc.ClientConnInterface) DropboxClient {
	return &dropboxClient{cc}
}

func (c *dropboxClient) GetApproverInfo(ctx context.Context, in *GetApproverInfoRequest, opts ...grpc.CallOption) (*GetApproverInfoResponse, error) {
	out := new(GetApproverInfoResponse)
	err := c.cc.Invoke(ctx, "/dropbox.Dropbox/GetApproverInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropboxClient) CanApproveToUser(ctx context.Context, in *CanApproveToUserRequest, opts ...grpc.CallOption) (*CanApproveToUserResponse, error) {
	out := new(CanApproveToUserResponse)
	err := c.cc.Invoke(ctx, "/dropbox.Dropbox/CanApproveToUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropboxClient) CreateRequest(ctx context.Context, in *CreateRequestRequest, opts ...grpc.CallOption) (*CreateRequestResponse, error) {
	out := new(CreateRequestResponse)
	err := c.cc.Invoke(ctx, "/dropbox.Dropbox/CreateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropboxClient) HasTransfer(ctx context.Context, in *HasTransferRequest, opts ...grpc.CallOption) (*HasTransferResponse, error) {
	out := new(HasTransferResponse)
	err := c.cc.Invoke(ctx, "/dropbox.Dropbox/HasTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropboxClient) GetTransfersInfo(ctx context.Context, in *GetTransfersInfoRequest, opts ...grpc.CallOption) (*GetTransfersInfoResponse, error) {
	out := new(GetTransfersInfoResponse)
	err := c.cc.Invoke(ctx, "/dropbox.Dropbox/GetTransfersInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DropboxServer is the server API for Dropbox service.
type DropboxServer interface {
	GetApproverInfo(context.Context, *GetApproverInfoRequest) (*GetApproverInfoResponse, error)
	CanApproveToUser(context.Context, *CanApproveToUserRequest) (*CanApproveToUserResponse, error)
	CreateRequest(context.Context, *CreateRequestRequest) (*CreateRequestResponse, error)
	HasTransfer(context.Context, *HasTransferRequest) (*HasTransferResponse, error)
	GetTransfersInfo(context.Context, *GetTransfersInfoRequest) (*GetTransfersInfoResponse, error)
}

// UnimplementedDropboxServer can be embedded to have forward compatible implementations.
type UnimplementedDropboxServer struct {
}

func (*UnimplementedDropboxServer) GetApproverInfo(ctx context.Context, req *GetApproverInfoRequest) (*GetApproverInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApproverInfo not implemented")
}
func (*UnimplementedDropboxServer) CanApproveToUser(ctx context.Context, req *CanApproveToUserRequest) (*CanApproveToUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanApproveToUser not implemented")
}
func (*UnimplementedDropboxServer) CreateRequest(ctx context.Context, req *CreateRequestRequest) (*CreateRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRequest not implemented")
}
func (*UnimplementedDropboxServer) HasTransfer(ctx context.Context, req *HasTransferRequest) (*HasTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasTransfer not implemented")
}
func (*UnimplementedDropboxServer) GetTransfersInfo(ctx context.Context, req *GetTransfersInfoRequest) (*GetTransfersInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransfersInfo not implemented")
}

func RegisterDropboxServer(s *grpc.Server, srv DropboxServer) {
	s.RegisterService(&_Dropbox_serviceDesc, srv)
}

func _Dropbox_GetApproverInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApproverInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropboxServer).GetApproverInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dropbox.Dropbox/GetApproverInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropboxServer).GetApproverInfo(ctx, req.(*GetApproverInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropbox_CanApproveToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanApproveToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropboxServer).CanApproveToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dropbox.Dropbox/CanApproveToUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropboxServer).CanApproveToUser(ctx, req.(*CanApproveToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropbox_CreateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropboxServer).CreateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dropbox.Dropbox/CreateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropboxServer).CreateRequest(ctx, req.(*CreateRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropbox_HasTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropboxServer).HasTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dropbox.Dropbox/HasTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropboxServer).HasTransfer(ctx, req.(*HasTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropbox_GetTransfersInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransfersInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropboxServer).GetTransfersInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dropbox.Dropbox/GetTransfersInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropboxServer).GetTransfersInfo(ctx, req.(*GetTransfersInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dropbox_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dropbox.Dropbox",
	HandlerType: (*DropboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApproverInfo",
			Handler:    _Dropbox_GetApproverInfo_Handler,
		},
		{
			MethodName: "CanApproveToUser",
			Handler:    _Dropbox_CanApproveToUser_Handler,
		},
		{
			MethodName: "CreateRequest",
			Handler:    _Dropbox_CreateRequest_Handler,
		},
		{
			MethodName: "HasTransfer",
			Handler:    _Dropbox_HasTransfer_Handler,
		},
		{
			MethodName: "GetTransfersInfo",
			Handler:    _Dropbox_GetTransfersInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dropbox/dropbox.proto",
}
